//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur10Mover
{
    [Serializable]
    public class ExecutionServiceRequest : Message
    {
        public const string k_RosMessageName = "ur10_mover/ExecutionService";
        public override string RosMessageName => k_RosMessageName;

        public ListOfFloatsMsg[] joint_states;

        public ExecutionServiceRequest()
        {
            this.joint_states = new ListOfFloatsMsg[0];
        }

        public ExecutionServiceRequest(ListOfFloatsMsg[] joint_states)
        {
            this.joint_states = joint_states;
        }

        public static ExecutionServiceRequest Deserialize(MessageDeserializer deserializer) => new ExecutionServiceRequest(deserializer);

        private ExecutionServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_states, ListOfFloatsMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.joint_states);
            serializer.Write(this.joint_states);
        }

        public override string ToString()
        {
            return "ExecutionServiceRequest: " +
            "\njoint_states: " + System.String.Join(", ", joint_states.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
