//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur10Mover
{
    [Serializable]
    public class GetTrainingDataServiceResponse : Message
    {
        public const string k_RosMessageName = "ur10_mover/GetTrainingDataService";
        public override string RosMessageName => k_RosMessageName;

        public ListOfPosesMsg[] trajectoryList;

        public GetTrainingDataServiceResponse()
        {
            this.trajectoryList = new ListOfPosesMsg[0];
        }

        public GetTrainingDataServiceResponse(ListOfPosesMsg[] trajectoryList)
        {
            this.trajectoryList = trajectoryList;
        }

        public static GetTrainingDataServiceResponse Deserialize(MessageDeserializer deserializer) => new GetTrainingDataServiceResponse(deserializer);

        private GetTrainingDataServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.trajectoryList, ListOfPosesMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.trajectoryList);
            serializer.Write(this.trajectoryList);
        }

        public override string ToString()
        {
            return "GetTrainingDataServiceResponse: " +
            "\ntrajectoryList: " + System.String.Join(", ", trajectoryList.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
