//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur10Mover
{
    [Serializable]
    public class PlannerServiceResponse : Message
    {
        public const string k_RosMessageName = "ur10_mover/PlannerService";
        public override string RosMessageName => k_RosMessageName;

        public string output_msg;
        public string request_type;
        public Geometry.PoseMsg[] pose_list;
        public Moveit.RobotTrajectoryMsg[] trajectories;

        public PlannerServiceResponse()
        {
            this.output_msg = "";
            this.request_type = "";
            this.pose_list = new Geometry.PoseMsg[0];
            this.trajectories = new Moveit.RobotTrajectoryMsg[0];
        }

        public PlannerServiceResponse(string output_msg, string request_type, Geometry.PoseMsg[] pose_list, Moveit.RobotTrajectoryMsg[] trajectories)
        {
            this.output_msg = output_msg;
            this.request_type = request_type;
            this.pose_list = pose_list;
            this.trajectories = trajectories;
        }

        public static PlannerServiceResponse Deserialize(MessageDeserializer deserializer) => new PlannerServiceResponse(deserializer);

        private PlannerServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.output_msg);
            deserializer.Read(out this.request_type);
            deserializer.Read(out this.pose_list, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.trajectories, Moveit.RobotTrajectoryMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.output_msg);
            serializer.Write(this.request_type);
            serializer.WriteLength(this.pose_list);
            serializer.Write(this.pose_list);
            serializer.WriteLength(this.trajectories);
            serializer.Write(this.trajectories);
        }

        public override string ToString()
        {
            return "PlannerServiceResponse: " +
            "\noutput_msg: " + output_msg.ToString() +
            "\nrequest_type: " + request_type.ToString() +
            "\npose_list: " + System.String.Join(", ", pose_list.ToList()) +
            "\ntrajectories: " + System.String.Join(", ", trajectories.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
