//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur10Mover
{
    [Serializable]
    public class SampleServiceRequest : Message
    {
        public const string k_RosMessageName = "ur10_mover/SampleService";
        public override string RosMessageName => k_RosMessageName;

        public string input_msg;
        public Geometry.PoseMsg start_point;
        public Geometry.PoseMsg end_point;

        public SampleServiceRequest()
        {
            this.input_msg = "";
            this.start_point = new Geometry.PoseMsg();
            this.end_point = new Geometry.PoseMsg();
        }

        public SampleServiceRequest(string input_msg, Geometry.PoseMsg start_point, Geometry.PoseMsg end_point)
        {
            this.input_msg = input_msg;
            this.start_point = start_point;
            this.end_point = end_point;
        }

        public static SampleServiceRequest Deserialize(MessageDeserializer deserializer) => new SampleServiceRequest(deserializer);

        private SampleServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.input_msg);
            this.start_point = Geometry.PoseMsg.Deserialize(deserializer);
            this.end_point = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.input_msg);
            serializer.Write(this.start_point);
            serializer.Write(this.end_point);
        }

        public override string ToString()
        {
            return "SampleServiceRequest: " +
            "\ninput_msg: " + input_msg.ToString() +
            "\nstart_point: " + start_point.ToString() +
            "\nend_point: " + end_point.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
