//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur10Mover
{
    [Serializable]
    public class SampleServiceRequest : Message
    {
        public const string k_RosMessageName = "ur10_mover/SampleService";
        public override string RosMessageName => k_RosMessageName;

        public string input_msg;
        public Geometry.PoseMsg[] condition_poses;
        public double context;

        public SampleServiceRequest()
        {
            this.input_msg = "";
            this.condition_poses = new Geometry.PoseMsg[0];
            this.context = 0.0;
        }

        public SampleServiceRequest(string input_msg, Geometry.PoseMsg[] condition_poses, double context)
        {
            this.input_msg = input_msg;
            this.condition_poses = condition_poses;
            this.context = context;
        }

        public static SampleServiceRequest Deserialize(MessageDeserializer deserializer) => new SampleServiceRequest(deserializer);

        private SampleServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.input_msg);
            deserializer.Read(out this.condition_poses, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.context);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.input_msg);
            serializer.WriteLength(this.condition_poses);
            serializer.Write(this.condition_poses);
            serializer.Write(this.context);
        }

        public override string ToString()
        {
            return "SampleServiceRequest: " +
            "\ninput_msg: " + input_msg.ToString() +
            "\ncondition_poses: " + System.String.Join(", ", condition_poses.ToList()) +
            "\ncontext: " + context.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
