//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur10Mover
{
    [Serializable]
    public class StateServiceResponse : Message
    {
        public const string k_RosMessageName = "ur10_mover/StateService";
        public override string RosMessageName => k_RosMessageName;

        public string output_msg;
        public double[] current_joint_angles;

        public StateServiceResponse()
        {
            this.output_msg = "";
            this.current_joint_angles = new double[6];
        }

        public StateServiceResponse(string output_msg, double[] current_joint_angles)
        {
            this.output_msg = output_msg;
            this.current_joint_angles = current_joint_angles;
        }

        public static StateServiceResponse Deserialize(MessageDeserializer deserializer) => new StateServiceResponse(deserializer);

        private StateServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.output_msg);
            deserializer.Read(out this.current_joint_angles, sizeof(double), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.output_msg);
            serializer.Write(this.current_joint_angles);
        }

        public override string ToString()
        {
            return "StateServiceResponse: " +
            "\noutput_msg: " + output_msg.ToString() +
            "\ncurrent_joint_angles: " + System.String.Join(", ", current_joint_angles.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
