//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur10Mover
{
    [Serializable]
    public class TrainingServiceRequest : Message
    {
        public const string k_RosMessageName = "ur10_mover/TrainingService";
        public override string RosMessageName => k_RosMessageName;

        public string input_msg;

        public TrainingServiceRequest()
        {
            this.input_msg = "";
        }

        public TrainingServiceRequest(string input_msg)
        {
            this.input_msg = input_msg;
        }

        public static TrainingServiceRequest Deserialize(MessageDeserializer deserializer) => new TrainingServiceRequest(deserializer);

        private TrainingServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.input_msg);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.input_msg);
        }

        public override string ToString()
        {
            return "TrainingServiceRequest: " +
            "\ninput_msg: " + input_msg.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
