//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterMaintenance
{
    [Serializable]
    public class CalibrateArmDataMsg : Message
    {
        public const string k_RosMessageName = "baxter_maintenance_msgs/CalibrateArmData";
        public override string RosMessageName => k_RosMessageName;

        public bool suppressWriteToFile;

        public CalibrateArmDataMsg()
        {
            this.suppressWriteToFile = false;
        }

        public CalibrateArmDataMsg(bool suppressWriteToFile)
        {
            this.suppressWriteToFile = suppressWriteToFile;
        }

        public static CalibrateArmDataMsg Deserialize(MessageDeserializer deserializer) => new CalibrateArmDataMsg(deserializer);

        private CalibrateArmDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.suppressWriteToFile);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.suppressWriteToFile);
        }

        public override string ToString()
        {
            return "CalibrateArmDataMsg: " +
            "\nsuppressWriteToFile: " + suppressWriteToFile.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
