//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterMaintenance
{
    [Serializable]
    public class TareEnableMsg : Message
    {
        public const string k_RosMessageName = "baxter_maintenance_msgs/TareEnable";
        public override string RosMessageName => k_RosMessageName;

        public bool isEnabled;
        public string uid;
        public TareDataMsg data;

        public TareEnableMsg()
        {
            this.isEnabled = false;
            this.uid = "";
            this.data = new TareDataMsg();
        }

        public TareEnableMsg(bool isEnabled, string uid, TareDataMsg data)
        {
            this.isEnabled = isEnabled;
            this.uid = uid;
            this.data = data;
        }

        public static TareEnableMsg Deserialize(MessageDeserializer deserializer) => new TareEnableMsg(deserializer);

        private TareEnableMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.isEnabled);
            deserializer.Read(out this.uid);
            this.data = TareDataMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.isEnabled);
            serializer.Write(this.uid);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "TareEnableMsg: " +
            "\nisEnabled: " + isEnabled.ToString() +
            "\nuid: " + uid.ToString() +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
