//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterMaintenance
{
    [Serializable]
    public class TareDataMsg : Message
    {
        public const string k_RosMessageName = "baxter_maintenance_msgs/TareData";
        public override string RosMessageName => k_RosMessageName;

        public bool tuneGravitySpring;

        public TareDataMsg()
        {
            this.tuneGravitySpring = false;
        }

        public TareDataMsg(bool tuneGravitySpring)
        {
            this.tuneGravitySpring = tuneGravitySpring;
        }

        public static TareDataMsg Deserialize(MessageDeserializer deserializer) => new TareDataMsg(deserializer);

        private TareDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.tuneGravitySpring);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.tuneGravitySpring);
        }

        public override string ToString()
        {
            return "TareDataMsg: " +
            "\ntuneGravitySpring: " + tuneGravitySpring.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
