//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterMaintenance
{
    [Serializable]
    public class UpdateSourceMsg : Message
    {
        public const string k_RosMessageName = "baxter_maintenance_msgs/UpdateSource";
        public override string RosMessageName => k_RosMessageName;

        public string devname;
        public string filename;
        public string version;
        public string uuid;

        public UpdateSourceMsg()
        {
            this.devname = "";
            this.filename = "";
            this.version = "";
            this.uuid = "";
        }

        public UpdateSourceMsg(string devname, string filename, string version, string uuid)
        {
            this.devname = devname;
            this.filename = filename;
            this.version = version;
            this.uuid = uuid;
        }

        public static UpdateSourceMsg Deserialize(MessageDeserializer deserializer) => new UpdateSourceMsg(deserializer);

        private UpdateSourceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.devname);
            deserializer.Read(out this.filename);
            deserializer.Read(out this.version);
            deserializer.Read(out this.uuid);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.devname);
            serializer.Write(this.filename);
            serializer.Write(this.version);
            serializer.Write(this.uuid);
        }

        public override string ToString()
        {
            return "UpdateSourceMsg: " +
            "\ndevname: " + devname.ToString() +
            "\nfilename: " + filename.ToString() +
            "\nversion: " + version.ToString() +
            "\nuuid: " + uuid.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
