// Generated by gencpp from file ur10_mover/ExecutionService.msg
// DO NOT EDIT!


#ifndef UR10_MOVER_MESSAGE_EXECUTIONSERVICE_H
#define UR10_MOVER_MESSAGE_EXECUTIONSERVICE_H

#include <ros/service_traits.h>


#include <ur10_mover/ExecutionServiceRequest.h>
#include <ur10_mover/ExecutionServiceResponse.h>


namespace ur10_mover
{

struct ExecutionService
{

typedef ExecutionServiceRequest Request;
typedef ExecutionServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecutionService
} // namespace ur10_mover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur10_mover::ExecutionService > {
  static const char* value()
  {
    return "200ed2e45e29d7b67fa3d65a61af734d";
  }

  static const char* value(const ::ur10_mover::ExecutionService&) { return value(); }
};

template<>
struct DataType< ::ur10_mover::ExecutionService > {
  static const char* value()
  {
    return "ur10_mover/ExecutionService";
  }

  static const char* value(const ::ur10_mover::ExecutionService&) { return value(); }
};


// service_traits::MD5Sum< ::ur10_mover::ExecutionServiceRequest> should match
// service_traits::MD5Sum< ::ur10_mover::ExecutionService >
template<>
struct MD5Sum< ::ur10_mover::ExecutionServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_mover::ExecutionService >::value();
  }
  static const char* value(const ::ur10_mover::ExecutionServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_mover::ExecutionServiceRequest> should match
// service_traits::DataType< ::ur10_mover::ExecutionService >
template<>
struct DataType< ::ur10_mover::ExecutionServiceRequest>
{
  static const char* value()
  {
    return DataType< ::ur10_mover::ExecutionService >::value();
  }
  static const char* value(const ::ur10_mover::ExecutionServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur10_mover::ExecutionServiceResponse> should match
// service_traits::MD5Sum< ::ur10_mover::ExecutionService >
template<>
struct MD5Sum< ::ur10_mover::ExecutionServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_mover::ExecutionService >::value();
  }
  static const char* value(const ::ur10_mover::ExecutionServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_mover::ExecutionServiceResponse> should match
// service_traits::DataType< ::ur10_mover::ExecutionService >
template<>
struct DataType< ::ur10_mover::ExecutionServiceResponse>
{
  static const char* value()
  {
    return DataType< ::ur10_mover::ExecutionService >::value();
  }
  static const char* value(const ::ur10_mover::ExecutionServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR10_MOVER_MESSAGE_EXECUTIONSERVICE_H
