// Generated by gencpp from file ur10_mover/GetTrainingDataServiceResponse.msg
// DO NOT EDIT!


#ifndef UR10_MOVER_MESSAGE_GETTRAININGDATASERVICERESPONSE_H
#define UR10_MOVER_MESSAGE_GETTRAININGDATASERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ur10_mover/ListOfPoses.h>

namespace ur10_mover
{
template <class ContainerAllocator>
struct GetTrainingDataServiceResponse_
{
  typedef GetTrainingDataServiceResponse_<ContainerAllocator> Type;

  GetTrainingDataServiceResponse_()
    : trajectoryList()  {
    }
  GetTrainingDataServiceResponse_(const ContainerAllocator& _alloc)
    : trajectoryList(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::ur10_mover::ListOfPoses_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ur10_mover::ListOfPoses_<ContainerAllocator> >> _trajectoryList_type;
  _trajectoryList_type trajectoryList;





  typedef boost::shared_ptr< ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTrainingDataServiceResponse_

typedef ::ur10_mover::GetTrainingDataServiceResponse_<std::allocator<void> > GetTrainingDataServiceResponse;

typedef boost::shared_ptr< ::ur10_mover::GetTrainingDataServiceResponse > GetTrainingDataServiceResponsePtr;
typedef boost::shared_ptr< ::ur10_mover::GetTrainingDataServiceResponse const> GetTrainingDataServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator1> & lhs, const ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.trajectoryList == rhs.trajectoryList;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator1> & lhs, const ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur10_mover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "911d3df46a7703daf3e95d9231abf0d7";
  }

  static const char* value(const ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x911d3df46a7703daULL;
  static const uint64_t static_value2 = 0xf3e95d9231abf0d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur10_mover/GetTrainingDataServiceResponse";
  }

  static const char* value(const ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur10_mover/ListOfPoses[] trajectoryList\n"
"\n"
"\n"
"================================================================================\n"
"MSG: ur10_mover/ListOfPoses\n"
"geometry_msgs/Pose[] pose_list\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trajectoryList);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTrainingDataServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur10_mover::GetTrainingDataServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "trajectoryList[]" << std::endl;
    for (size_t i = 0; i < v.trajectoryList.size(); ++i)
    {
      s << indent << "  trajectoryList[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ur10_mover::ListOfPoses_<ContainerAllocator> >::stream(s, indent + "    ", v.trajectoryList[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR10_MOVER_MESSAGE_GETTRAININGDATASERVICERESPONSE_H
