// Generated by gencpp from file ur10_mover/GetTrainingDataService.msg
// DO NOT EDIT!


#ifndef UR10_MOVER_MESSAGE_GETTRAININGDATASERVICE_H
#define UR10_MOVER_MESSAGE_GETTRAININGDATASERVICE_H

#include <ros/service_traits.h>


#include <ur10_mover/GetTrainingDataServiceRequest.h>
#include <ur10_mover/GetTrainingDataServiceResponse.h>


namespace ur10_mover
{

struct GetTrainingDataService
{

typedef GetTrainingDataServiceRequest Request;
typedef GetTrainingDataServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTrainingDataService
} // namespace ur10_mover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur10_mover::GetTrainingDataService > {
  static const char* value()
  {
    return "a23732bf635c86b0cb4cf0b1248e70e9";
  }

  static const char* value(const ::ur10_mover::GetTrainingDataService&) { return value(); }
};

template<>
struct DataType< ::ur10_mover::GetTrainingDataService > {
  static const char* value()
  {
    return "ur10_mover/GetTrainingDataService";
  }

  static const char* value(const ::ur10_mover::GetTrainingDataService&) { return value(); }
};


// service_traits::MD5Sum< ::ur10_mover::GetTrainingDataServiceRequest> should match
// service_traits::MD5Sum< ::ur10_mover::GetTrainingDataService >
template<>
struct MD5Sum< ::ur10_mover::GetTrainingDataServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_mover::GetTrainingDataService >::value();
  }
  static const char* value(const ::ur10_mover::GetTrainingDataServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_mover::GetTrainingDataServiceRequest> should match
// service_traits::DataType< ::ur10_mover::GetTrainingDataService >
template<>
struct DataType< ::ur10_mover::GetTrainingDataServiceRequest>
{
  static const char* value()
  {
    return DataType< ::ur10_mover::GetTrainingDataService >::value();
  }
  static const char* value(const ::ur10_mover::GetTrainingDataServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur10_mover::GetTrainingDataServiceResponse> should match
// service_traits::MD5Sum< ::ur10_mover::GetTrainingDataService >
template<>
struct MD5Sum< ::ur10_mover::GetTrainingDataServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_mover::GetTrainingDataService >::value();
  }
  static const char* value(const ::ur10_mover::GetTrainingDataServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_mover::GetTrainingDataServiceResponse> should match
// service_traits::DataType< ::ur10_mover::GetTrainingDataService >
template<>
struct DataType< ::ur10_mover::GetTrainingDataServiceResponse>
{
  static const char* value()
  {
    return DataType< ::ur10_mover::GetTrainingDataService >::value();
  }
  static const char* value(const ::ur10_mover::GetTrainingDataServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR10_MOVER_MESSAGE_GETTRAININGDATASERVICE_H
