// Generated by gencpp from file ur10_mover/GripperService.msg
// DO NOT EDIT!


#ifndef UR10_MOVER_MESSAGE_GRIPPERSERVICE_H
#define UR10_MOVER_MESSAGE_GRIPPERSERVICE_H

#include <ros/service_traits.h>


#include <ur10_mover/GripperServiceRequest.h>
#include <ur10_mover/GripperServiceResponse.h>


namespace ur10_mover
{

struct GripperService
{

typedef GripperServiceRequest Request;
typedef GripperServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GripperService
} // namespace ur10_mover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur10_mover::GripperService > {
  static const char* value()
  {
    return "b57e415505eb1ef8a5131e05d03cd81c";
  }

  static const char* value(const ::ur10_mover::GripperService&) { return value(); }
};

template<>
struct DataType< ::ur10_mover::GripperService > {
  static const char* value()
  {
    return "ur10_mover/GripperService";
  }

  static const char* value(const ::ur10_mover::GripperService&) { return value(); }
};


// service_traits::MD5Sum< ::ur10_mover::GripperServiceRequest> should match
// service_traits::MD5Sum< ::ur10_mover::GripperService >
template<>
struct MD5Sum< ::ur10_mover::GripperServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_mover::GripperService >::value();
  }
  static const char* value(const ::ur10_mover::GripperServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_mover::GripperServiceRequest> should match
// service_traits::DataType< ::ur10_mover::GripperService >
template<>
struct DataType< ::ur10_mover::GripperServiceRequest>
{
  static const char* value()
  {
    return DataType< ::ur10_mover::GripperService >::value();
  }
  static const char* value(const ::ur10_mover::GripperServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur10_mover::GripperServiceResponse> should match
// service_traits::MD5Sum< ::ur10_mover::GripperService >
template<>
struct MD5Sum< ::ur10_mover::GripperServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_mover::GripperService >::value();
  }
  static const char* value(const ::ur10_mover::GripperServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_mover::GripperServiceResponse> should match
// service_traits::DataType< ::ur10_mover::GripperService >
template<>
struct DataType< ::ur10_mover::GripperServiceResponse>
{
  static const char* value()
  {
    return DataType< ::ur10_mover::GripperService >::value();
  }
  static const char* value(const ::ur10_mover::GripperServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR10_MOVER_MESSAGE_GRIPPERSERVICE_H
