// Generated by gencpp from file ur10_mover/ListOfPoses.msg
// DO NOT EDIT!


#ifndef UR10_MOVER_MESSAGE_LISTOFPOSES_H
#define UR10_MOVER_MESSAGE_LISTOFPOSES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace ur10_mover
{
template <class ContainerAllocator>
struct ListOfPoses_
{
  typedef ListOfPoses_<ContainerAllocator> Type;

  ListOfPoses_()
    : pose_list()  {
    }
  ListOfPoses_(const ContainerAllocator& _alloc)
    : pose_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose_<ContainerAllocator> >> _pose_list_type;
  _pose_list_type pose_list;





  typedef boost::shared_ptr< ::ur10_mover::ListOfPoses_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur10_mover::ListOfPoses_<ContainerAllocator> const> ConstPtr;

}; // struct ListOfPoses_

typedef ::ur10_mover::ListOfPoses_<std::allocator<void> > ListOfPoses;

typedef boost::shared_ptr< ::ur10_mover::ListOfPoses > ListOfPosesPtr;
typedef boost::shared_ptr< ::ur10_mover::ListOfPoses const> ListOfPosesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur10_mover::ListOfPoses_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur10_mover::ListOfPoses_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur10_mover::ListOfPoses_<ContainerAllocator1> & lhs, const ::ur10_mover::ListOfPoses_<ContainerAllocator2> & rhs)
{
  return lhs.pose_list == rhs.pose_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur10_mover::ListOfPoses_<ContainerAllocator1> & lhs, const ::ur10_mover::ListOfPoses_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur10_mover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ur10_mover::ListOfPoses_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_mover::ListOfPoses_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10_mover::ListOfPoses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10_mover::ListOfPoses_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_mover::ListOfPoses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_mover::ListOfPoses_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur10_mover::ListOfPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e5f9729e6eac8b890e586b463fdbada";
  }

  static const char* value(const ::ur10_mover::ListOfPoses_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e5f9729e6eac8b8ULL;
  static const uint64_t static_value2 = 0x90e586b463fdbadaULL;
};

template<class ContainerAllocator>
struct DataType< ::ur10_mover::ListOfPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur10_mover/ListOfPoses";
  }

  static const char* value(const ::ur10_mover::ListOfPoses_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur10_mover::ListOfPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose[] pose_list\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::ur10_mover::ListOfPoses_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur10_mover::ListOfPoses_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListOfPoses_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur10_mover::ListOfPoses_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur10_mover::ListOfPoses_<ContainerAllocator>& v)
  {
    s << indent << "pose_list[]" << std::endl;
    for (size_t i = 0; i < v.pose_list.size(); ++i)
    {
      s << indent << "  pose_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.pose_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR10_MOVER_MESSAGE_LISTOFPOSES_H
