// Generated by gencpp from file ur10_mover/PlannerServiceRequest.msg
// DO NOT EDIT!


#ifndef UR10_MOVER_MESSAGE_PLANNERSERVICEREQUEST_H
#define UR10_MOVER_MESSAGE_PLANNERSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace ur10_mover
{
template <class ContainerAllocator>
struct PlannerServiceRequest_
{
  typedef PlannerServiceRequest_<ContainerAllocator> Type;

  PlannerServiceRequest_()
    : input_msg()
    , request_type()
    , joints_input()
    , pose_list()  {
      joints_input.assign(0.0);
  }
  PlannerServiceRequest_(const ContainerAllocator& _alloc)
    : input_msg(_alloc)
    , request_type(_alloc)
    , joints_input()
    , pose_list(_alloc)  {
  (void)_alloc;
      joints_input.assign(0.0);
  }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _input_msg_type;
  _input_msg_type input_msg;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _request_type_type;
  _request_type_type request_type;

   typedef boost::array<double, 6>  _joints_input_type;
  _joints_input_type joints_input;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose_<ContainerAllocator> >> _pose_list_type;
  _pose_list_type pose_list;





  typedef boost::shared_ptr< ::ur10_mover::PlannerServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur10_mover::PlannerServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlannerServiceRequest_

typedef ::ur10_mover::PlannerServiceRequest_<std::allocator<void> > PlannerServiceRequest;

typedef boost::shared_ptr< ::ur10_mover::PlannerServiceRequest > PlannerServiceRequestPtr;
typedef boost::shared_ptr< ::ur10_mover::PlannerServiceRequest const> PlannerServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur10_mover::PlannerServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur10_mover::PlannerServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur10_mover::PlannerServiceRequest_<ContainerAllocator1> & lhs, const ::ur10_mover::PlannerServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input_msg == rhs.input_msg &&
    lhs.request_type == rhs.request_type &&
    lhs.joints_input == rhs.joints_input &&
    lhs.pose_list == rhs.pose_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur10_mover::PlannerServiceRequest_<ContainerAllocator1> & lhs, const ::ur10_mover::PlannerServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur10_mover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ur10_mover::PlannerServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_mover::PlannerServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10_mover::PlannerServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10_mover::PlannerServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_mover::PlannerServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_mover::PlannerServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur10_mover::PlannerServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "457198907edcc0113dfed24d6746788d";
  }

  static const char* value(const ::ur10_mover::PlannerServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x457198907edcc011ULL;
  static const uint64_t static_value2 = 0x3dfed24d6746788dULL;
};

template<class ContainerAllocator>
struct DataType< ::ur10_mover::PlannerServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur10_mover/PlannerServiceRequest";
  }

  static const char* value(const ::ur10_mover::PlannerServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur10_mover::PlannerServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string input_msg\n"
"string request_type\n"
"float64[6] joints_input\n"
"geometry_msgs/Pose[] pose_list\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::ur10_mover::PlannerServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur10_mover::PlannerServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input_msg);
      stream.next(m.request_type);
      stream.next(m.joints_input);
      stream.next(m.pose_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlannerServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur10_mover::PlannerServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur10_mover::PlannerServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "input_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.input_msg);
    s << indent << "request_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.request_type);
    s << indent << "joints_input[]" << std::endl;
    for (size_t i = 0; i < v.joints_input.size(); ++i)
    {
      s << indent << "  joints_input[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joints_input[i]);
    }
    s << indent << "pose_list[]" << std::endl;
    for (size_t i = 0; i < v.pose_list.size(); ++i)
    {
      s << indent << "  pose_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.pose_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR10_MOVER_MESSAGE_PLANNERSERVICEREQUEST_H
