// Generated by gencpp from file ur10_mover/SampleServiceRequest.msg
// DO NOT EDIT!


#ifndef UR10_MOVER_MESSAGE_SAMPLESERVICEREQUEST_H
#define UR10_MOVER_MESSAGE_SAMPLESERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace ur10_mover
{
template <class ContainerAllocator>
struct SampleServiceRequest_
{
  typedef SampleServiceRequest_<ContainerAllocator> Type;

  SampleServiceRequest_()
    : input_msg()
    , condition_poses()
    , context(0.0)  {
    }
  SampleServiceRequest_(const ContainerAllocator& _alloc)
    : input_msg(_alloc)
    , condition_poses(_alloc)
    , context(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _input_msg_type;
  _input_msg_type input_msg;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose_<ContainerAllocator> >> _condition_poses_type;
  _condition_poses_type condition_poses;

   typedef double _context_type;
  _context_type context;





  typedef boost::shared_ptr< ::ur10_mover::SampleServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur10_mover::SampleServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SampleServiceRequest_

typedef ::ur10_mover::SampleServiceRequest_<std::allocator<void> > SampleServiceRequest;

typedef boost::shared_ptr< ::ur10_mover::SampleServiceRequest > SampleServiceRequestPtr;
typedef boost::shared_ptr< ::ur10_mover::SampleServiceRequest const> SampleServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur10_mover::SampleServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur10_mover::SampleServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur10_mover::SampleServiceRequest_<ContainerAllocator1> & lhs, const ::ur10_mover::SampleServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input_msg == rhs.input_msg &&
    lhs.condition_poses == rhs.condition_poses &&
    lhs.context == rhs.context;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur10_mover::SampleServiceRequest_<ContainerAllocator1> & lhs, const ::ur10_mover::SampleServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur10_mover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ur10_mover::SampleServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_mover::SampleServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10_mover::SampleServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10_mover::SampleServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_mover::SampleServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_mover::SampleServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur10_mover::SampleServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80b48f9c302347801e022f4750bf5612";
  }

  static const char* value(const ::ur10_mover::SampleServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80b48f9c30234780ULL;
  static const uint64_t static_value2 = 0x1e022f4750bf5612ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur10_mover::SampleServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur10_mover/SampleServiceRequest";
  }

  static const char* value(const ::ur10_mover::SampleServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur10_mover::SampleServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string input_msg\n"
"geometry_msgs/Pose[] condition_poses\n"
"float64 context\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::ur10_mover::SampleServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur10_mover::SampleServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input_msg);
      stream.next(m.condition_poses);
      stream.next(m.context);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SampleServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur10_mover::SampleServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur10_mover::SampleServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "input_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.input_msg);
    s << indent << "condition_poses[]" << std::endl;
    for (size_t i = 0; i < v.condition_poses.size(); ++i)
    {
      s << indent << "  condition_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.condition_poses[i]);
    }
    s << indent << "context: ";
    Printer<double>::stream(s, indent + "  ", v.context);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR10_MOVER_MESSAGE_SAMPLESERVICEREQUEST_H
