// Generated by gencpp from file ur10_mover/TrainingService.msg
// DO NOT EDIT!


#ifndef UR10_MOVER_MESSAGE_TRAININGSERVICE_H
#define UR10_MOVER_MESSAGE_TRAININGSERVICE_H

#include <ros/service_traits.h>


#include <ur10_mover/TrainingServiceRequest.h>
#include <ur10_mover/TrainingServiceResponse.h>


namespace ur10_mover
{

struct TrainingService
{

typedef TrainingServiceRequest Request;
typedef TrainingServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TrainingService
} // namespace ur10_mover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur10_mover::TrainingService > {
  static const char* value()
  {
    return "b57e415505eb1ef8a5131e05d03cd81c";
  }

  static const char* value(const ::ur10_mover::TrainingService&) { return value(); }
};

template<>
struct DataType< ::ur10_mover::TrainingService > {
  static const char* value()
  {
    return "ur10_mover/TrainingService";
  }

  static const char* value(const ::ur10_mover::TrainingService&) { return value(); }
};


// service_traits::MD5Sum< ::ur10_mover::TrainingServiceRequest> should match
// service_traits::MD5Sum< ::ur10_mover::TrainingService >
template<>
struct MD5Sum< ::ur10_mover::TrainingServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_mover::TrainingService >::value();
  }
  static const char* value(const ::ur10_mover::TrainingServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_mover::TrainingServiceRequest> should match
// service_traits::DataType< ::ur10_mover::TrainingService >
template<>
struct DataType< ::ur10_mover::TrainingServiceRequest>
{
  static const char* value()
  {
    return DataType< ::ur10_mover::TrainingService >::value();
  }
  static const char* value(const ::ur10_mover::TrainingServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur10_mover::TrainingServiceResponse> should match
// service_traits::MD5Sum< ::ur10_mover::TrainingService >
template<>
struct MD5Sum< ::ur10_mover::TrainingServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_mover::TrainingService >::value();
  }
  static const char* value(const ::ur10_mover::TrainingServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_mover::TrainingServiceResponse> should match
// service_traits::DataType< ::ur10_mover::TrainingService >
template<>
struct DataType< ::ur10_mover::TrainingServiceResponse>
{
  static const char* value()
  {
    return DataType< ::ur10_mover::TrainingService >::value();
  }
  static const char* value(const ::ur10_mover::TrainingServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR10_MOVER_MESSAGE_TRAININGSERVICE_H
