// Generated by gencpp from file ur10_mover/TrainingDataService.msg
// DO NOT EDIT!


#ifndef UR10_MOVER_MESSAGE_TRAININGDATASERVICE_H
#define UR10_MOVER_MESSAGE_TRAININGDATASERVICE_H

#include <ros/service_traits.h>


#include <ur10_mover/TrainingDataServiceRequest.h>
#include <ur10_mover/TrainingDataServiceResponse.h>


namespace ur10_mover
{

struct TrainingDataService
{

typedef TrainingDataServiceRequest Request;
typedef TrainingDataServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TrainingDataService
} // namespace ur10_mover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur10_mover::TrainingDataService > {
  static const char* value()
  {
    return "2553c089c44939195fc3dab519dd2853";
  }

  static const char* value(const ::ur10_mover::TrainingDataService&) { return value(); }
};

template<>
struct DataType< ::ur10_mover::TrainingDataService > {
  static const char* value()
  {
    return "ur10_mover/TrainingDataService";
  }

  static const char* value(const ::ur10_mover::TrainingDataService&) { return value(); }
};


// service_traits::MD5Sum< ::ur10_mover::TrainingDataServiceRequest> should match
// service_traits::MD5Sum< ::ur10_mover::TrainingDataService >
template<>
struct MD5Sum< ::ur10_mover::TrainingDataServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_mover::TrainingDataService >::value();
  }
  static const char* value(const ::ur10_mover::TrainingDataServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_mover::TrainingDataServiceRequest> should match
// service_traits::DataType< ::ur10_mover::TrainingDataService >
template<>
struct DataType< ::ur10_mover::TrainingDataServiceRequest>
{
  static const char* value()
  {
    return DataType< ::ur10_mover::TrainingDataService >::value();
  }
  static const char* value(const ::ur10_mover::TrainingDataServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur10_mover::TrainingDataServiceResponse> should match
// service_traits::MD5Sum< ::ur10_mover::TrainingDataService >
template<>
struct MD5Sum< ::ur10_mover::TrainingDataServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_mover::TrainingDataService >::value();
  }
  static const char* value(const ::ur10_mover::TrainingDataServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_mover::TrainingDataServiceResponse> should match
// service_traits::DataType< ::ur10_mover::TrainingDataService >
template<>
struct DataType< ::ur10_mover::TrainingDataServiceResponse>
{
  static const char* value()
  {
    return DataType< ::ur10_mover::TrainingDataService >::value();
  }
  static const char* value(const ::ur10_mover::TrainingDataServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR10_MOVER_MESSAGE_TRAININGDATASERVICE_H
