//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur10Mover
{
    [Serializable]
    public class ListOfFloatsMsg : Message
    {
        public const string k_RosMessageName = "ur10_mover/ListOfFloats";
        public override string RosMessageName => k_RosMessageName;

        public double[] list;

        public ListOfFloatsMsg()
        {
            this.list = new double[0];
        }

        public ListOfFloatsMsg(double[] list)
        {
            this.list = list;
        }

        public static ListOfFloatsMsg Deserialize(MessageDeserializer deserializer) => new ListOfFloatsMsg(deserializer);

        private ListOfFloatsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.list, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.list);
            serializer.Write(this.list);
        }

        public override string ToString()
        {
            return "ListOfFloatsMsg: " +
            "\nlist: " + System.String.Join(", ", list.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
