//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur10Mover
{
    [Serializable]
    public class ListOfPosesMsg : Message
    {
        public const string k_RosMessageName = "ur10_mover/ListOfPoses";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg[] pose_list;

        public ListOfPosesMsg()
        {
            this.pose_list = new Geometry.PoseMsg[0];
        }

        public ListOfPosesMsg(Geometry.PoseMsg[] pose_list)
        {
            this.pose_list = pose_list;
        }

        public static ListOfPosesMsg Deserialize(MessageDeserializer deserializer) => new ListOfPosesMsg(deserializer);

        private ListOfPosesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pose_list, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.pose_list);
            serializer.Write(this.pose_list);
        }

        public override string ToString()
        {
            return "ListOfPosesMsg: " +
            "\npose_list: " + System.String.Join(", ", pose_list.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
