//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ros
{
    [Serializable]
    public class MoverServiceRequest : Message
    {
        public const string k_RosMessageName = "Ros/MoverService";
        public override string RosMessageName => k_RosMessageName;

        public string input_msg;
        public double[] joints_input;
        public Geometry.PoseMsg[] pose_list;

        public MoverServiceRequest()
        {
            this.input_msg = "";
            this.joints_input = new double[6];
            this.pose_list = new Geometry.PoseMsg[0];
        }

        public MoverServiceRequest(string input_msg, double[] joints_input, Geometry.PoseMsg[] pose_list)
        {
            this.input_msg = input_msg;
            this.joints_input = joints_input;
            this.pose_list = pose_list;
        }

        public static MoverServiceRequest Deserialize(MessageDeserializer deserializer) => new MoverServiceRequest(deserializer);

        private MoverServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.input_msg);
            deserializer.Read(out this.joints_input, sizeof(double), 6);
            deserializer.Read(out this.pose_list, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.input_msg);
            serializer.Write(this.joints_input);
            serializer.WriteLength(this.pose_list);
            serializer.Write(this.pose_list);
        }

        public override string ToString()
        {
            return "MoverServiceRequest: " +
            "\ninput_msg: " + input_msg.ToString() +
            "\njoints_input: " + System.String.Join(", ", joints_input.ToList()) +
            "\npose_list: " + System.String.Join(", ", pose_list.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
