//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unity
{
    [Serializable]
    public class IKHelperUnityRequest : Message
    {
        public const string k_RosMessageName = "unity/IKHelperUnity";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg pose;
        public string arm;

        public IKHelperUnityRequest()
        {
            this.pose = new Geometry.PoseMsg();
            this.arm = "";
        }

        public IKHelperUnityRequest(Geometry.PoseMsg pose, string arm)
        {
            this.pose = pose;
            this.arm = arm;
        }

        public static IKHelperUnityRequest Deserialize(MessageDeserializer deserializer) => new IKHelperUnityRequest(deserializer);

        private IKHelperUnityRequest(MessageDeserializer deserializer)
        {
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.arm);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose);
            serializer.Write(this.arm);
        }

        public override string ToString()
        {
            return "IKHelperUnityRequest: " +
            "\npose: " + pose.ToString() +
            "\narm: " + arm.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
