//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterCore
{
    [Serializable]
    public class CloseCameraRequest : Message
    {
        public const string k_RosMessageName = "baxter_core_msgs/CloseCamera";
        public override string RosMessageName => k_RosMessageName;

        public string name;

        public CloseCameraRequest()
        {
            this.name = "";
        }

        public CloseCameraRequest(string name)
        {
            this.name = name;
        }

        public static CloseCameraRequest Deserialize(MessageDeserializer deserializer) => new CloseCameraRequest(deserializer);

        private CloseCameraRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "CloseCameraRequest: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
