//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterCore
{
    [Serializable]
    public class CloseCameraResponse : Message
    {
        public const string k_RosMessageName = "baxter_core_msgs/CloseCamera";
        public override string RosMessageName => k_RosMessageName;

        public int err;

        public CloseCameraResponse()
        {
            this.err = 0;
        }

        public CloseCameraResponse(int err)
        {
            this.err = err;
        }

        public static CloseCameraResponse Deserialize(MessageDeserializer deserializer) => new CloseCameraResponse(deserializer);

        private CloseCameraResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.err);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.err);
        }

        public override string ToString()
        {
            return "CloseCameraResponse: " +
            "\nerr: " + err.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
