//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterCore
{
    [Serializable]
    public class ListCamerasResponse : Message
    {
        public const string k_RosMessageName = "baxter_core_msgs/ListCameras";
        public override string RosMessageName => k_RosMessageName;

        public string[] cameras;

        public ListCamerasResponse()
        {
            this.cameras = new string[0];
        }

        public ListCamerasResponse(string[] cameras)
        {
            this.cameras = cameras;
        }

        public static ListCamerasResponse Deserialize(MessageDeserializer deserializer) => new ListCamerasResponse(deserializer);

        private ListCamerasResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cameras, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.cameras);
            serializer.Write(this.cameras);
        }

        public override string ToString()
        {
            return "ListCamerasResponse: " +
            "\ncameras: " + System.String.Join(", ", cameras.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
