//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterCore
{
    [Serializable]
    public class OpenCameraRequest : Message
    {
        public const string k_RosMessageName = "baxter_core_msgs/OpenCamera";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public CameraSettingsMsg settings;

        public OpenCameraRequest()
        {
            this.name = "";
            this.settings = new CameraSettingsMsg();
        }

        public OpenCameraRequest(string name, CameraSettingsMsg settings)
        {
            this.name = name;
            this.settings = settings;
        }

        public static OpenCameraRequest Deserialize(MessageDeserializer deserializer) => new OpenCameraRequest(deserializer);

        private OpenCameraRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            this.settings = CameraSettingsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.settings);
        }

        public override string ToString()
        {
            return "OpenCameraRequest: " +
            "\nname: " + name.ToString() +
            "\nsettings: " + settings.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
