//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterCore
{
    [Serializable]
    public class OpenCameraResponse : Message
    {
        public const string k_RosMessageName = "baxter_core_msgs/OpenCamera";
        public override string RosMessageName => k_RosMessageName;

        public int err;

        public OpenCameraResponse()
        {
            this.err = 0;
        }

        public OpenCameraResponse(int err)
        {
            this.err = err;
        }

        public static OpenCameraResponse Deserialize(MessageDeserializer deserializer) => new OpenCameraResponse(deserializer);

        private OpenCameraResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.err);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.err);
        }

        public override string ToString()
        {
            return "OpenCameraResponse: " +
            "\nerr: " + err.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
