//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterCore
{
    [Serializable]
    public class AnalogOutputCommandMsg : Message
    {
        public const string k_RosMessageName = "baxter_core_msgs/AnalogOutputCommand";
        public override string RosMessageName => k_RosMessageName;

        // #the name of the output
        public string name;
        // #the value to set output 
        public ushort value;

        public AnalogOutputCommandMsg()
        {
            this.name = "";
            this.value = 0;
        }

        public AnalogOutputCommandMsg(string name, ushort value)
        {
            this.name = name;
            this.value = value;
        }

        public static AnalogOutputCommandMsg Deserialize(MessageDeserializer deserializer) => new AnalogOutputCommandMsg(deserializer);

        private AnalogOutputCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "AnalogOutputCommandMsg: " +
            "\nname: " + name.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
