//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterCore
{
    [Serializable]
    public class CameraSettingsMsg : Message
    {
        public const string k_RosMessageName = "baxter_core_msgs/CameraSettings";
        public override string RosMessageName => k_RosMessageName;

        public int width;
        public int height;
        public float fps;
        public CameraControlMsg[] controls;

        public CameraSettingsMsg()
        {
            this.width = 0;
            this.height = 0;
            this.fps = 0.0f;
            this.controls = new CameraControlMsg[0];
        }

        public CameraSettingsMsg(int width, int height, float fps, CameraControlMsg[] controls)
        {
            this.width = width;
            this.height = height;
            this.fps = fps;
            this.controls = controls;
        }

        public static CameraSettingsMsg Deserialize(MessageDeserializer deserializer) => new CameraSettingsMsg(deserializer);

        private CameraSettingsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.width);
            deserializer.Read(out this.height);
            deserializer.Read(out this.fps);
            deserializer.Read(out this.controls, CameraControlMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.width);
            serializer.Write(this.height);
            serializer.Write(this.fps);
            serializer.WriteLength(this.controls);
            serializer.Write(this.controls);
        }

        public override string ToString()
        {
            return "CameraSettingsMsg: " +
            "\nwidth: " + width.ToString() +
            "\nheight: " + height.ToString() +
            "\nfps: " + fps.ToString() +
            "\ncontrols: " + System.String.Join(", ", controls.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
