//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterCore
{
    [Serializable]
    public class CollisionDetectionStateMsg : Message
    {
        public const string k_RosMessageName = "baxter_core_msgs/CollisionDetectionState";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public bool collision_state;

        public CollisionDetectionStateMsg()
        {
            this.header = new Std.HeaderMsg();
            this.collision_state = false;
        }

        public CollisionDetectionStateMsg(Std.HeaderMsg header, bool collision_state)
        {
            this.header = header;
            this.collision_state = collision_state;
        }

        public static CollisionDetectionStateMsg Deserialize(MessageDeserializer deserializer) => new CollisionDetectionStateMsg(deserializer);

        private CollisionDetectionStateMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.collision_state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.collision_state);
        }

        public override string ToString()
        {
            return "CollisionDetectionStateMsg: " +
            "\nheader: " + header.ToString() +
            "\ncollision_state: " + collision_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
