//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterCore
{
    [Serializable]
    public class DigitalIOStateMsg : Message
    {
        public const string k_RosMessageName = "baxter_core_msgs/DigitalIOState";
        public override string RosMessageName => k_RosMessageName;

        public sbyte state;
        public bool isInputOnly;
        public const sbyte OFF = 0;
        public const sbyte ON = 1;
        public const sbyte PRESSED = 1;
        public const sbyte UNPRESSED = 0;

        public DigitalIOStateMsg()
        {
            this.state = 0;
            this.isInputOnly = false;
        }

        public DigitalIOStateMsg(sbyte state, bool isInputOnly)
        {
            this.state = state;
            this.isInputOnly = isInputOnly;
        }

        public static DigitalIOStateMsg Deserialize(MessageDeserializer deserializer) => new DigitalIOStateMsg(deserializer);

        private DigitalIOStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
            deserializer.Read(out this.isInputOnly);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
            serializer.Write(this.isInputOnly);
        }

        public override string ToString()
        {
            return "DigitalIOStateMsg: " +
            "\nstate: " + state.ToString() +
            "\nisInputOnly: " + isInputOnly.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
