//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterCore
{
    [Serializable]
    public class JointCommandMsg : Message
    {
        public const string k_RosMessageName = "baxter_core_msgs/JointCommand";
        public override string RosMessageName => k_RosMessageName;

        public int mode;
        public double[] command;
        public string[] names;
        public const int POSITION_MODE = 1;
        public const int VELOCITY_MODE = 2;
        public const int TORQUE_MODE = 3;
        public const int RAW_POSITION_MODE = 4;

        public JointCommandMsg()
        {
            this.mode = 0;
            this.command = new double[0];
            this.names = new string[0];
        }

        public JointCommandMsg(int mode, double[] command, string[] names)
        {
            this.mode = mode;
            this.command = command;
            this.names = names;
        }

        public static JointCommandMsg Deserialize(MessageDeserializer deserializer) => new JointCommandMsg(deserializer);

        private JointCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
            deserializer.Read(out this.command, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.names, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
            serializer.WriteLength(this.command);
            serializer.Write(this.command);
            serializer.WriteLength(this.names);
            serializer.Write(this.names);
        }

        public override string ToString()
        {
            return "JointCommandMsg: " +
            "\nmode: " + mode.ToString() +
            "\ncommand: " + System.String.Join(", ", command.ToList()) +
            "\nnames: " + System.String.Join(", ", names.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
