//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterCore
{
    [Serializable]
    public class NavigatorStatesMsg : Message
    {
        public const string k_RosMessageName = "baxter_core_msgs/NavigatorStates";
        public override string RosMessageName => k_RosMessageName;

        //  used when publishing multiple navigators
        public string[] names;
        public NavigatorStateMsg[] states;

        public NavigatorStatesMsg()
        {
            this.names = new string[0];
            this.states = new NavigatorStateMsg[0];
        }

        public NavigatorStatesMsg(string[] names, NavigatorStateMsg[] states)
        {
            this.names = names;
            this.states = states;
        }

        public static NavigatorStatesMsg Deserialize(MessageDeserializer deserializer) => new NavigatorStatesMsg(deserializer);

        private NavigatorStatesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.names, deserializer.ReadLength());
            deserializer.Read(out this.states, NavigatorStateMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.names);
            serializer.Write(this.names);
            serializer.WriteLength(this.states);
            serializer.Write(this.states);
        }

        public override string ToString()
        {
            return "NavigatorStatesMsg: " +
            "\nnames: " + System.String.Join(", ", names.ToList()) +
            "\nstates: " + System.String.Join(", ", states.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
